import { writeFileSync } from 'node:fs'

// Generate src/styles/cursors.css — an ORIGINAL, token-driven XP-style cursor
// set (no Microsoft bitmaps). Cursors are hand-drawn SVGs encoded as data URIs
// and exposed as :root custom properties so a future visual style can override
// them. Applied OS-wide with !important because in XP nearly everything is the
// arrow (incl. buttons — the hand is only for hyperlinks), which lets one rule
// correct the many component-level `cursor: pointer/default` declarations.

const svg = (body, w = 24, h = 24) =>
  `<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}' viewBox='0 0 ${w} ${h}'>${body}</svg>`

// Classic pointer arrow — tip at top-left (hotspot 1,1).
const ARROW = svg(
  `<path d='M1.5 1 L1.5 17.5 L5.8 13.6 L8.7 20 L11.1 19 L8.3 12.9 L13.8 12.9 Z' fill='#fff' stroke='#000' stroke-width='1.2' stroke-linejoin='round'/>`,
)

// Link hand — index finger up over a folded fist (hotspot ~8,1).
const HAND = svg(
  `<path d='M8 2.5 C8 1.2 10 1.2 10 2.5 L10 9 L11 9 L11 6.4 C11 5.2 13 5.2 13 6.4 L13 9.4 L14 9.4 L14 7.2 C14 6 16 6 16 7.2 L16 9.8 L17 9.8 L17 8.6 C17 7.5 19 7.5 19 8.6 L19 16 C19 18.8 17 20.8 14.2 20.8 L12.4 20.8 C10.6 20.8 9.4 20 8.4 18.4 L5.2 13.2 C4.5 12 6.2 10.7 7.1 11.7 L8 12.7 Z' fill='#fff' stroke='#000' stroke-width='1.1' stroke-linejoin='round'/>`,
)

// Wait hourglass (hotspot center 12,12).
const BUSY = svg(
  `<path d='M6 3 H18 V4.5 Q18 5.5 17 6.4 L13 11 L17 15.6 Q18 16.5 18 17.5 V21 H6 V17.5 Q6 16.5 7 15.6 L11 11 L7 6.4 Q6 5.5 6 4.5 Z' fill='#fff' stroke='#000' stroke-width='1.2' stroke-linejoin='round'/>` +
    `<path d='M8.5 5 H15.5 L12 9 Z' fill='#000'/><path d='M9 19 H15 L12 14.5 Z' fill='#000'/>`,
)

// Double-headed resize arrow (vertical base shape); rotated for each direction.
const dArrow = (deg) =>
  svg(
    `<g transform='rotate(${deg} 12 12)'><path d='M12 2 L7.5 7 H10.5 V17 H7.5 L12 22 L16.5 17 H13.5 V7 H16.5 Z' fill='#fff' stroke='#000' stroke-width='1.2' stroke-linejoin='round'/></g>`,
  )

const cur = (s, hx, hy, fallback) =>
  `url("data:image/svg+xml,${encodeURIComponent(s)}") ${hx} ${hy}, ${fallback}`

const vars = {
  '--cur-arrow': cur(ARROW, 1, 1, 'default'),
  '--cur-hand': cur(HAND, 8, 1, 'pointer'),
  '--cur-busy': cur(BUSY, 12, 12, 'wait'),
  '--cur-ns': cur(dArrow(0), 12, 12, 'ns-resize'),
  '--cur-ew': cur(dArrow(90), 12, 12, 'ew-resize'),
  '--cur-nesw': cur(dArrow(45), 12, 12, 'nesw-resize'),
  '--cur-nwse': cur(dArrow(135), 12, 12, 'nwse-resize'),
}

const css = `/* GENERATED by scripts/make-cursors.mjs — do not edit by hand.
   Original XP-style cursor theme (no Microsoft bitmaps). Token-driven so a
   visual style can override --cur-* later. See the generator for the SVG art. */
:root {
${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n')}
}

/* Arrow everywhere — overrides the many component cursor:pointer/default decls
   (XP shows the arrow on buttons too; only the exceptions below differ). */
*, *::before, *::after { cursor: var(--cur-arrow) !important; }

/* Hyperlinks → hand (the one place XP uses it). */
a[href], [data-cur="hand"] { cursor: var(--cur-hand) !important; }

/* Text entry → I-beam (skip non-text input types). */
input:not([type="button"]):not([type="submit"]):not([type="reset"]):not([type="range"]):not([type="checkbox"]):not([type="radio"]):not([type="color"]):not([type="file"]),
textarea,
[contenteditable="true"],
.monaco-editor .view-lines,
.monaco-editor textarea { cursor: var(--cur-text, text) !important; }

/* Busy — the Suspense fallback already sets aria-busy. */
[aria-busy="true"], [data-cur="busy"] { cursor: var(--cur-busy) !important; }

/* Full-screen overlays that hide the pointer (screensaver, BSOD, games). */
[data-cursor-hidden], [data-cursor-hidden] * { cursor: none !important; }
`

writeFileSync(new URL('../src/styles/cursors.css', import.meta.url), css)
console.log('wrote src/styles/cursors.css (' + css.length + ' bytes)')
